/* native_caps.c -- the capability each builtin interpreter native requires.
 *
 * security-audit-plan WP3 (S-1).  Every native that turi_env_new registers --
 * interpreter_natives.c, collections_native.c, string_native.c, fiber.c, the
 * eval.c builtins, macro_env.c, ffi_thunk.c and main.c -- has exactly one row
 * here.  turi_env_register_native looks the name up and stamps the row's bits
 * on the closure; eval_apply_driven refuses the call when the calling env does
 * not hold every one of them.  One check at the dispatch, not one per native.
 *
 * A row of 0 is "pure": the native reaches nothing outside the interpreter's
 * own heap.  Classification is by what the CALLER can make the native do, so a
 * native that writes stderr only on its own panic path is still 0.  What a 0
 * row does NOT promise is memory safety: most natives take handles as bare
 * integers, and refusing a forged one is the handle-signature column's job
 * (S-5 in the security audit plan; k_handle_rows[] below).
 *
 * Rules for a new native:
 *   - add its row here, in strcmp order (the table is binary-searched);
 *   - tests/turi/sandbox-eval.c fails for any native a fresh env holds that has
 *     no row, and for any non-zero row a sandboxed env can call;
 *   - the reason goes in the trailing comment of every non-zero row.
 *
 * Natives an embedder registers under a name that is not in this table carry
 * no requirement: the embedder chose to expose them.  Use
 * turi_env_register_native_caps to give one a requirement explicitly.
 *
 * The prose version, with the rationale for each class, is the "Capability
 * classification" table in docs/guides/sandboxing-guide.md. */
#include <string.h>

#include "turi/eval.h"

static const TuriNativeCapRow k_rows[] = {
    { "Mock-Time", 0 },
    { "Mock-Time-free", 0 },
    { "__identity_duplicate", 0 },
    { "__identity_extract", 0 },
    { "__identity_get", 0 },
    { "__identity_new", 0 },
    { "__inst_Eq_eq_qu_Sym", 0 },
    { "__inst_Hash_hash_Sym", 0 },
    { "__inst_Hash_hash_cstr", 0 },
    { "__inst_Hash_hash_float", 0 },
    { "__inst_Hash_hash_float32", 0 },
    { "__inst_MapKey_mk_hybox_Sym", 0 },
    { "__inst_MapKey_mk_hybox_cstr", 0 },
    { "__inst_MapKey_mk_hybox_float", 0 },
    { "__inst_MapKey_mk_hybox_float32", 0 },
    { "__inst_MapKey_mk_hycmp_Sym", 0 },
    { "__inst_MapKey_mk_hycmp_cstr", 0 },
    { "__inst_MapKey_mk_hycmp_float", 0 },
    { "__inst_MapKey_mk_hycmp_float32", 0 },
    { "__inst_MapKey_mk_hycmp_int", 0 },
    { "__inst_Serializable_deserialize_bool", 0 },
    { "__inst_Serializable_deserialize_int", 0 },
    { "__inst_Serializable_serialize_bool", 0 },
    { "__inst_Serializable_serialize_int", 0 },
    { "__inst_Show_show_bool", 0 },
    { "__inst_Show_show_cstr", 0 },
    { "__inst_Show_show_float", 0 },
    { "__inst_Show_show_float32", 0 },
    { "__inst_Show_show_int", 0 },
    { "__inst_Show_show_int16", 0 },
    { "__inst_Show_show_int32", 0 },
    { "__inst_Show_show_int8", 0 },
    { "__inst_Show_show_uint16", 0 },
    { "__inst_Show_show_uint32", 0 },
    { "__inst_Show_show_uint64", 0 },
    { "__inst_Show_show_uint8", 0 },
    { "__pair_duplicate", 0 },
    { "__pair_env", 0 },
    { "__pair_extract", 0 },
    { "__pair_new", 0 },
    { "__pair_val", 0 },
    { "__sized-buf-copy!-raw", 0 },
    { "__sized-buf-fill!-raw", 0 },
    { "__sized-buf-free-raw", 0 },
    { "__sized-buf-get-raw", 0 },
    { "__sized-buf-len-raw", 0 },
    { "__sized-buf-max-raw", 0 },
    { "__sized-buf-min-raw", 0 },
    { "__sized-buf-new-raw", 0 },
    { "__sized-buf-new-zeroed-raw", 0 },
    { "__sized-buf-set!-raw", 0 },
    { "__sized-buf-sum-raw", 0 },
    { "acos", 0 },
    { "alloc-int", TURI_CAP_UNSAFE },                        /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "alloc-key", TURI_CAP_UNSAFE },                        /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "alloc-str", TURI_CAP_UNSAFE },                        /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "array-get", TURI_CAP_UNSAFE },                        /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "array-set", TURI_CAP_UNSAFE },                        /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "asin", 0 },
    { "async-all2", TURI_CAP_ASYNC },                        /* scheduler entry points, same gate as (async ...) */
    { "async-chan-count", 0 },
    { "async-chan-free", 0 },
    { "async-chan-new", 0 },
    { "async-chan-try-recv", 0 },
    { "async-chan-try-send", 0 },
    { "async-pipe-init", TURI_CAP_IO },                      /* pipe(2) */
    { "async-pipe-rfd", 0 },
    { "async-pipe-wfd", 0 },
    { "async-race", TURI_CAP_ASYNC },                        /* scheduler entry points, same gate as (async ...) */
    { "atan", 0 },
    { "atan2", 0 },
    { "await-val", TURI_CAP_ASYNC },                         /* scheduler entry points, same gate as (async ...) */
    { "bit-shr", 0 },
    { "bit-xor", 0 },
    { "bits->float", 0 },
    { "bool->syntax", 0 },
    { "box", TURI_CAP_UNSAFE },                              /* the native twins of the ptr-deref / raw-malloc builtins */
    { "break", TURI_CAP_IO },                                /* interactive debugger prompt on stdin */
    { "bt-apply-fat", 0 },
    { "bt-bound?", 0 },
    { "bt-cell-free", 0 },
    { "bt-cell-new", 0 },
    { "bt-commit-to!", 0 },
    { "bt-cons", 0 },
    { "bt-depth", 0 },
    { "bt-get", 0 },
    { "bt-length", 0 },
    { "bt-level", 0 },
    { "bt-lvar-new", 0 },
    { "bt-mark", 0 },
    { "bt-nil", 0 },
    { "bt-print", TURI_CAP_IO },                             /* writes stdout */
    { "bt-set!", 0 },
    { "bt-undo-to!", 0 },
    { "bytes-alloc", 0 },
    { "bytes-data", 0 },
    { "bytes-free", 0 },
    { "bytes-len", 0 },
    { "c-abs", 0 },
    { "cancel-task", TURI_CAP_ASYNC },                       /* scheduler entry points, same gate as (async ...) */
    { "ceil", 0 },
    { "chan-free", 0 },
    { "chan-new", 0 },
    { "chan-recv", 0 },
    { "chan-send", 0 },
    { "cons", 0 },
    { "contract-enabled?", 0 },
    { "cos", 0 },
    { "cstr->parse-int", 0 },
    { "cstr-free", 0 },
    { "cstr-len", 0 },
    { "cstr-nth", 0 },
    { "cstr-sub", 0 },
    { "doc-lookup", 0 },
    { "doc-print", TURI_CAP_IO },                            /* writes stdout */
    { "err", 0 },
    { "err-val", 0 },
    { "err-val-ptr", 0 },
    { "err?", 0 },
    { "error", 0 },
    { "error-message", 0 },
    { "error?", 0 },
    { "exp", 0 },
    { "fabs", 0 },
    { "flat-get", TURI_CAP_UNSAFE },                         /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "flat-new", TURI_CAP_UNSAFE },                         /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "flat-set", TURI_CAP_UNSAFE },                         /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "float->bits", 0 },
    { "float->int", 0 },
    { "float->syntax", 0 },
    { "floor", 0 },
    { "free-bind", 0 },
    { "free-run", 0 },
    { "fs/tmpfile", TURI_CAP_FS },                           /* mkstemp in /tmp */
    { "fs/tmpfile-fd", TURI_CAP_FS },                        /* a tmpfile handle: its path, its fd, and unlink */
    { "fs/tmpfile-free", TURI_CAP_FS },                      /* a tmpfile handle: its path, its fd, and unlink */
    { "fs/tmpfile-path", TURI_CAP_FS },                      /* a tmpfile handle: its path, its fd, and unlink */
    { "future-cell-free", 0 },
    { "future-cell-new", 0 },
    { "future-done?", 0 },
    { "future-free", 0 },
    { "future-handle", 0 },
    { "g-cell-free", 0 },
    { "g-cell-new", 0 },
    { "g-get", 0 },
    { "g-set!", 0 },
    { "gen-arr-get", 0 },
    { "gen-arr-len", 0 },
    { "gen-arr-new", 0 },
    { "gen-arr-push!", 0 },
    { "gen-none", 0 },
    { "gen-some?", 0 },
    { "gen-unwrap", 0 },
    { "grid-free", 0 },
    { "grid-get", 0 },
    { "grid-height", 0 },
    { "grid-new", 0 },
    { "grid-set!", 0 },
    { "grid-width", 0 },
    { "hamt-free", 0 },
    { "hamt-get", 0 },
    { "hamt-hash-ptr", 0 },
    { "hamt-new", 0 },
    { "hamt-set", 0 },
    { "head", 0 },
    { "int->float", 0 },
    { "int->str", 0 },
    { "int->syntax", 0 },
    { "int->unit-float", 0 },
    { "int-val", TURI_CAP_UNSAFE },                          /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "io-alloc", TURI_CAP_UNSAFE },                         /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "io-buf-free", TURI_CAP_UNSAFE },                      /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "io-buf-new", TURI_CAP_UNSAFE },                       /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "io-fclose", TURI_CAP_FS },                            /* stdio on a FILE* from io-fopen-*; no pure use */
    { "io-fopen-read", TURI_CAP_FS },                        /* fopen by path */
    { "io-fopen-write", TURI_CAP_FS },                       /* fopen by path */
    { "io-fread-chunk", TURI_CAP_FS },                       /* stdio on a FILE* from io-fopen-*; no pure use */
    { "io-free", TURI_CAP_UNSAFE },                          /* raw malloc/free or deref of a caller-supplied address, no typed wrapper */
    { "io-fwrite-chunk", TURI_CAP_FS },                      /* stdio on a FILE* from io-fopen-*; no pure use */
    { "io-remove", TURI_CAP_FS },                            /* remove/unlink by path */
    { "json/array-get", 0 },
    { "json/array-len", 0 },
    { "json/array-new", 0 },
    { "json/array-push", 0 },
    { "json/bool", 0 },
    { "json/decode", 0 },
    { "json/decode-file!", TURI_CAP_FS },                    /* reads a file by path */
    { "json/encode", 0 },
    { "json/float", 0 },
    { "json/free", 0 },
    { "json/get", 0 },
    { "json/get!", 0 },
    { "json/get-bool", 0 },
    { "json/get-float", 0 },
    { "json/get-int", 0 },
    { "json/get-string", 0 },
    { "json/int", 0 },
    { "json/null", 0 },
    { "json/object-new", 0 },
    { "json/object-put", 0 },
    { "json/string", 0 },
    { "json/type", 0 },
    { "k-apply-raw", 0 },
    { "kw->syntax", 0 },
    { "list-head", 0 },
    { "list-length", 0 },
    { "list-nil?", 0 },
    { "list-tail", 0 },
    { "log", 0 },
    { "map-assoc-eq", 0 },
    { "map-assoc-eq-o", 0 },
    { "map-count", 0 },
    { "map-dissoc-eq", 0 },
    { "map-dissoc-eq-o", 0 },
    { "map-eq-raw-k?", 0 },
    { "map-eq-raw?", 0 },
    { "map-free", 0 },
    { "map-get-dynamic-as", 0 },
    { "map-get-eq", 0 },
    { "map-get-eq-o", 0 },
    { "map-hamt", 0 },
    { "map-has-eq-o?", 0 },
    { "map-has-eq?", 0 },
    { "map-iter-cur-val-as", 0 },
    { "map-merge", 0 },
    { "map-new", 0 },
    { "mbind", 0 },
    { "mock-time-get", 0 },
    { "mock-time-set", 0 },
    { "mplus", 0 },
    { "mreturn", 0 },
    { "mutex-free", 0 },
    { "mutex-lock", 0 },
    { "mutex-new", 0 },
    { "mutex-try-lock", 0 },
    { "mutex-unlock", 0 },
    { "mutmap-cap", 0 },
    { "mutmap-delete!", 0 },
    { "mutmap-eq-storage?", 0 },
    { "mutmap-free", 0 },
    { "mutmap-get", 0 },
    { "mutmap-has?", 0 },
    { "mutmap-len", 0 },
    { "mutmap-new", 0 },
    { "mutmap-set!", 0 },
    { "mutmap-slot-hash", 0 },
    { "mutmap-slot-key", 0 },
    { "mutmap-slot-occupied?", 0 },
    { "mutmap-slot-value", 0 },
    { "mutmap-storage-field__", 0 },
    { "mzero", 0 },
    { "nil->syntax", 0 },
    { "nil-value", 0 },
    { "none", 0 },
    { "ok", 0 },
    { "ok-val", 0 },
    { "ok-val-ptr", 0 },
    { "ok?", 0 },
    { "option-eq?", 0 },
    { "option-expect", 0 },
    { "option-free", 0 },
    { "option-map", 0 },
    { "option-must", 0 },
    { "option-unwrap", 0 },
    { "option-unwrap-or", 0 },
    { "option-value", 0 },
    { "panic?", 0 },
    { "popcount", 0 },
    { "pow", 0 },
    { "println-float", TURI_CAP_IO },                        /* writes stdout */
    { "process/child-of-raw", TURI_CAP_PROC },               /* pid -> ChildHandle */
    { "process/spawn-raw", TURI_CAP_PROC },                  /* fork+execvp */
    { "process/wait-raw", TURI_CAP_PROC },                   /* waitpid */
    { "promise-fulfill", 0 },
    { "ptr=", 0 },
    { "r7rs-args-head__", 0 },
    { "r7rs-args-tail__", 0 },
    { "r7rs-bar-symbol__", 0 },
    { "r7rs-big->float__", 0 },
    { "r7rs-big-cmp-float__", 0 },
    { "r7rs-big-cmp__", 0 },
    { "r7rs-big-fits?__", 0 },
    { "r7rs-big-int__", 0 },
    { "r7rs-big-op__", 0 },
    { "r7rs-big-radix__", 0 },
    { "r7rs-blen__", 0 },
    { "r7rs-bsubstring__", 0 },
    { "r7rs-call-variadic__", 0 },
    { "r7rs-cont-capture__", 0 },
    { "r7rs-cont-here?__", 0 },
    { "r7rs-cont-null?__", 0 },
    { "r7rs-cont-restore__", 0 },
    { "r7rs-cont-resumed?__", 0 },
    { "r7rs-cstr-free__", 0 },
    { "r7rs-cstr-hash__", 0 },
    { "r7rs-cstr<__", 0 },
    { "r7rs-current-jiffy", 0 },
    { "r7rs-current-second", 0 },
    { "r7rs-dyn-ref__", 0 },
    { "r7rs-dyn-set__", 0 },
    { "r7rs-dyn-unset?__", 0 },
    { "r7rs-environ-count__", TURI_CAP_ENV },                /* getenv / environ */
    { "r7rs-environ-name__", TURI_CAP_ENV },                 /* getenv / environ */
    { "r7rs-environ-value__", TURI_CAP_ENV },                /* getenv / environ */
    { "r7rs-escape-string__", 0 },
    { "r7rs-eval-c-answer-datum__", TURI_CAP_EVERY },        /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-answer-host__", TURI_CAP_EVERY },         /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-answer-proc__", TURI_CAP_EVERY },         /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-answer-raise__", TURI_CAP_EVERY },        /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-answer-unspecified__", TURI_CAP_EVERY },  /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-apply__", TURI_CAP_EVERY },               /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-eval__", TURI_CAP_EVERY },                /* evaluates text in the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-frame-count__", TURI_CAP_EVERY },         /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-frame-id__", TURI_CAP_EVERY },            /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-frame-kind__", TURI_CAP_EVERY },          /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-frame-text__", TURI_CAP_EVERY },          /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-load__", TURI_CAP_EVERY },                /* reads a file and evaluates it in the embedded R7RS env (every capability) */
    { "r7rs-eval-c-push-datum__", TURI_CAP_EVERY },          /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-push-host__", TURI_CAP_EVERY },           /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-push-proc__", TURI_CAP_EVERY },           /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-result-id__", TURI_CAP_EVERY },           /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-eval-c-result-text__", TURI_CAP_EVERY },         /* acts on the process-global embedded R7RS env, which holds every capability */
    { "r7rs-exact-of-float__", 0 },
    { "r7rs-exit__", TURI_CAP_PROC },                        /* exit() -- ends the host process */
    { "r7rs-file-exists-c__", TURI_CAP_FS },                 /* stat by path (existence oracle) */
    { "r7rs-float->big__", 0 },
    { "r7rs-float->string__", 0 },
    { "r7rs-float-infinite?__", 0 },
    { "r7rs-float-integral?__", 0 },
    { "r7rs-float-nan?__", 0 },
    { "r7rs-getenv-set?__", TURI_CAP_ENV },                  /* getenv / environ */
    { "r7rs-getenv__", TURI_CAP_ENV },                       /* getenv / environ */
    { "r7rs-identity-word__", 0 },
    { "r7rs-idtab-count__", 0 },
    { "r7rs-idtab-free__", 0 },
    { "r7rs-idtab-get__", 0 },
    { "r7rs-idtab-new__", 0 },
    { "r7rs-idtab-put__", 0 },
    { "r7rs-int->string-radix__", 0 },
    { "r7rs-int->string__", 0 },
    { "r7rs-int-ovf?__", 0 },
    { "r7rs-io-add-byte__", 0 },
    { "r7rs-io-add__", 0 },
    { "r7rs-io-byte-ref__", 0 },
    { "r7rs-io-close__", 0 },
    { "r7rs-io-flush__", 0 },
    { "r7rs-io-free__", 0 },
    { "r7rs-io-len__", 0 },
    { "r7rs-io-new__", 0 },
    { "r7rs-io-ok?__", 0 },
    { "r7rs-io-open__", TURI_CAP_FS },                       /* fopen by path */
    { "r7rs-io-peek__", 0 },
    { "r7rs-io-ready?__", 0 },
    { "r7rs-io-skip__", 0 },
    { "r7rs-io-std__", TURI_CAP_IO },                        /* the stdin/stdout/stderr port handles */
    { "r7rs-io-str__", 0 },
    { "r7rs-numsyn-big__", 0 },
    { "r7rs-numsyn-float__", 0 },
    { "r7rs-numsyn-int__", 0 },
    { "r7rs-numsyn-kind__", 0 },
    { "r7rs-numsyn-part__", 0 },
    { "r7rs-numsyn-why__", 0 },
    { "r7rs-raise-type__", 0 },
    { "r7rs-ratio->float__", 0 },
    { "r7rs-ratio-part__", 0 },
    { "r7rs-same-ref__", 0 },
    { "r7rs-string-append2__", 0 },
    { "r7rs-string-of-code__", 0 },
    { "r7rs-string-ref-code__", 0 },
    { "r7rs-symbol-plain?__", 0 },
    { "r7rs-thread-lock-c__", 0 },
    { "r7rs-thread-monitor__", 0 },
    { "r7rs-thread-notify-c__", 0 },
    { "r7rs-thread-now__", 0 },
    { "r7rs-thread-sleep__", 0 },
    { "r7rs-thread-spawn-c__", TURI_CAP_ASYNC },                 /* starts a scheduler fiber, same gate as (async ...) */
    { "r7rs-thread-unlock-c__", 0 },
    { "r7rs-thread-wait-c__", 0 },
    { "r7rs-thread-yield__", 0 },
    { "r7rs-toplevel__", 0 },
    { "r7rs-type-error-hook-install__", 0 },
    { "r7rs-uc-map__", 0 },
    { "r7rs-uc-prop__", 0 },
    { "r7rs-uc-run__", 0 },
    { "r7rs-uc-string__", 0 },
    { "r7rs-unlink__", TURI_CAP_FS },                        /* remove/unlink by path */
    { "r7rs-utf8-at__", 0 },
    { "r7rs-utf8-count__", 0 },
    { "r7rs-utf8-ref__", 0 },
    { "r7rs-variadic-fixed__", 0 },
    { "random-access-bench", TURI_CAP_FS | TURI_CAP_IO },    /* benchmark helper: temp file + stdout */
    { "reactor-new", TURI_CAP_IO },                          /* epoll/kqueue fd and a blocking poll */
    { "read-async", TURI_CAP_IO },                           /* read(2)/write(2) on a caller-supplied raw fd -- 0/1/2 need no open */
    { "read-string", 0 },
    { "reload", TURI_CAP_FFI },                              /* reloads the dlopened spice image */
    { "result-collect", 0 },
    { "result-debug", 0 },
    { "result-display", 0 },
    { "result-eq?", 0 },
    { "result-error-message", 0 },
    { "result-expect", 0 },
    { "result-flat-map", 0 },
    { "result-free", 0 },
    { "result-map", 0 },
    { "result-map-err", 0 },
    { "result-must", 0 },
    { "result-must-msg", 0 },
    { "result-or", 0 },
    { "result-or-else", 0 },
    { "result-partition", 0 },
    { "result-partition-err", 0 },
    { "result-partition-ok", 0 },
    { "result-unwrap", 0 },
    { "result-unwrap-err", 0 },
    { "result-unwrap-or", 0 },
    { "resume-cont!", 0 },
    { "rint", 0 },
    { "run-nbody", TURI_CAP_IO },                            /* writes stdout */
    { "run-raytracer", 0 },
    { "run-ring", TURI_CAP_IO },                             /* writes stdout */
    { "save-cont!", 0 },
    { "schan-advance-recv", 0 },
    { "schan-close", 0 },
    { "schan-new", 0 },
    { "schan-recv-value", 0 },
    { "schan-send", 0 },
    { "schema-decode", 0 },
    { "schema-decode-abort", 0 },
    { "schema-decode-errors", 0 },
    { "schema-decode-ok?", 0 },
    { "schema-decode-value", 0 },
    { "schema-error-at", 0 },
    { "schema-error-count", 0 },
    { "schema-error-message", 0 },
    { "schema-error-path", 0 },
    { "schema-error-text", 0 },
    { "schema/always", 0 },
    { "schema/ap", 0 },
    { "schema/ap-fat", 0 },
    { "schema/array", 0 },
    { "schema/bool", 0 },
    { "schema/field", 0 },
    { "schema/field-of", 0 },
    { "schema/float", 0 },
    { "schema/fmap", 0 },
    { "schema/int", 0 },
    { "schema/kind", 0 },
    { "schema/literal-int", 0 },
    { "schema/literal-str", 0 },
    { "schema/never", 0 },
    { "schema/nil", 0 },
    { "schema/object-new", 0 },
    { "schema/optional", 0 },
    { "schema/rec", 0 },
    { "schema/str", 0 },
    { "schema/transform", 0 },
    { "schema/union", 0 },
    { "seq-call-bool-fn1", 0 },
    { "seq-call-fn0", 0 },
    { "seq-call-fn1", 0 },
    { "seq-call-fn2", 0 },
    { "seq-call-void-fn1", 0 },
    { "seq-gen-done", 0 },
    { "seq-gen-done-int", 0 },
    { "seq-gen-from-int", 0 },
    { "seq-gen-next", 0 },
    { "seq-gen-next-int", 0 },
    { "seq-gen-to-int", 0 },
    { "seq-iter", 0 },
    { "seq-list-head", 0 },
    { "seq-list-nil?", 0 },
    { "seq-list-tail", 0 },
    { "seq-make-cons", 0 },
    { "seq-make-none", 0 },
    { "seq-make-pair", 0 },
    { "seq-make-some", 0 },
    { "seq-opt-some?", 0 },
    { "seq-opt-unwrap", 0 },
    { "seq-out-vec-new", 0 },
    { "seq-out-vec-push!", 0 },
    { "seq-pair-first", 0 },
    { "seq-pair-second", 0 },
    { "seq-val-some?", 0 },
    { "seq-val-unwrap", 0 },
    { "seq-vec-get", 0 },
    { "seq-vec-len", 0 },
    { "session-join", 0 },
    { "session-spawn", 0 },
    { "set-add-eq-o", 0 },
    { "set-count", 0 },
    { "set-del-eq-o", 0 },
    { "set-diff", 0 },
    { "set-eq-cmp?", 0 },
    { "set-eq?", 0 },
    { "set-free", 0 },
    { "set-has-eq-o?", 0 },
    { "set-intersect", 0 },
    { "set-new", 0 },
    { "set-union", 0 },
    { "show-concat", 0 },
    { "show-float", 0 },
    { "show-int", 0 },
    { "show-string-fputs", TURI_CAP_IO },                    /* writes stdout */
    { "sin", 0 },
    { "sleep-async", TURI_CAP_ASYNC },                       /* scheduler entry points, same gate as (async ...) */
    { "sleep-ms", 0 },
    { "slice-free", 0 },
    { "slice-get", 0 },
    { "slice-len", 0 },
    { "slice-new", 0 },
    { "some", 0 },
    { "some?", 0 },
    { "sqrt", 0 },
    { "str->int", 0 },
    { "str->int-checked", 0 },
    { "str->sym", 0 },
    { "str->syntax", 0 },
    { "str-concat", 0 },
    { "strcmp", 0 },
    { "struct-hash", 0 },
    { "struct-key-cmp", 0 },
    { "sym->str", 0 },
    { "sym->syntax", 0 },
    { "sym=?", 0 },
    { "syntax->float", 0 },
    { "syntax->int", 0 },
    { "syntax->str", 0 },
    { "syntax->string", 0 },
    { "syntax-append", 0 },
    { "syntax-cons", 0 },
    { "syntax-error", 0 },
    { "syntax-first", 0 },
    { "syntax-float?", 0 },
    { "syntax-gensym", 0 },
    { "syntax-int?", 0 },
    { "syntax-keyword?", 0 },
    { "syntax-len", 0 },
    { "syntax-list", 0 },
    { "syntax-list?", 0 },
    { "syntax-nil?", 0 },
    { "syntax-nth", 0 },
    { "syntax-quote", 0 },
    { "syntax-rest", 0 },
    { "syntax-str?", 0 },
    { "syntax-struct-fields", 0 },
    { "syntax-sym-name", 0 },
    { "syntax-sym?", 0 },
    { "syntax-tag", 0 },
    { "syntax-type-ann", 0 },
    { "syntax-vec", 0 },
    { "syntax-vec?", 0 },
    { "syntax=?", 0 },
    { "tail", 0 },
    { "tan", 0 },
    { "task-cancelled?", TURI_CAP_ASYNC },                   /* scheduler entry points, same gate as (async ...) */
    { "task-group-cancel", 0 },
    { "task-group-cancelled?", 0 },
    { "task-group-free", 0 },
    { "task-group-new", 0 },
    { "task-group-wait", 0 },
    { "trail-reset!", 0 },
    { "trunc", 0 },
    { "tuple2-eq-carrier?", 0 },
    { "tur-contract-check", 0 },
    { "tur-contract-check-at", 0 },
    { "tur-contract-check-inv", 0 },
    { "tur-map-homog__", 0 },
    { "tur-sqrt", 0 },
    { "tur-vec-homog__", 0 },
    { "tur_hamt_count", 0 },
    { "tur_hamt_del", 0 },
    { "tur_hamt_del_cstr", 0 },
    { "tur_hamt_free", 0 },
    { "tur_hamt_get", 0 },
    { "tur_hamt_get_cstr", 0 },
    { "tur_hamt_get_dynamic", 0 },
    { "tur_hamt_has", 0 },
    { "tur_hamt_has_cstr", 0 },
    { "tur_hamt_has_dynamic", 0 },
    { "tur_hamt_hash_ptr", 0 },
    { "tur_hamt_hash_str", 0 },
    { "tur_hamt_iter_advance", 0 },
    { "tur_hamt_iter_alloc", 0 },
    { "tur_hamt_iter_cur_hash", 0 },
    { "tur_hamt_iter_cur_key", 0 },
    { "tur_hamt_iter_cur_val", 0 },
    { "tur_hamt_iter_destroy", 0 },
    { "tur_hamt_iter_free", 0 },
    { "tur_hamt_iter_init", 0 },
    { "tur_hamt_iter_next", 0 },
    { "tur_hamt_keyeq", 0 },
    { "tur_hamt_merge", 0 },
    { "tur_hamt_merge_with", 0 },
    { "tur_hamt_new", 0 },
    { "tur_hamt_persistent", 0 },
    { "tur_hamt_retain", 0 },
    { "tur_hamt_set", 0 },
    { "tur_hamt_set_cstr", 0 },
    { "tur_hamt_show", 0 },
    { "tur_hamt_transient", 0 },
    { "tur_hamt_transient_del", 0 },
    { "tur_hamt_transient_set", 0 },
    { "tur_reactor_free", 0 },
    { "tur_reactor_new", TURI_CAP_IO },                      /* epoll/kqueue fd and a blocking poll */
    { "tur_reactor_poll", TURI_CAP_IO },                     /* epoll/kqueue fd and a blocking poll */
    { "tur_sb_finish", 0 },
    { "tur_sb_len", 0 },
    { "tur_sb_new", 0 },
    { "tur_sb_push_byte", 0 },
    { "tur_sb_push_cstr", 0 },
    { "tur_sb_push_string", 0 },
    { "tur_slice_byte_at", 0 },
    { "tur_slice_cmp", 0 },
    { "tur_slice_empty", 0 },
    { "tur_slice_eq", 0 },
    { "tur_slice_hash", 0 },
    { "tur_slice_len", 0 },
    { "tur_slice_release", 0 },
    { "tur_slice_retain", 0 },
    { "tur_slice_sub", 0 },
    { "tur_slice_to_cstr", 0 },
    { "tur_slice_to_string", 0 },
    { "tur_string_adopt_cstr", 0 },
    { "tur_string_box_key", 0 },
    { "tur_string_byte_at", 0 },
    { "tur_string_cmp", 0 },
    { "tur_string_concat", 0 },
    { "tur_string_contains", 0 },
    { "tur_string_cstr", 0 },
    { "tur_string_empty", 0 },
    { "tur_string_ends_with", 0 },
    { "tur_string_eq", 0 },
    { "tur_string_from_bytes", 0 },
    { "tur_string_from_cstr", 0 },
    { "tur_string_from_int", 0 },
    { "tur_string_hash", 0 },
    { "tur_string_key_eq_addr", 0 },
    { "tur_string_len", 0 },
    { "tur_string_release", 0 },
    { "tur_string_retain", 0 },
    { "tur_string_slice", 0 },
    { "tur_string_slice_cstr", 0 },
    { "tur_string_starts_with", 0 },
    { "tur_string_substring", 0 },
    { "tur_string_to_lower", 0 },
    { "tur_string_to_upper", 0 },
    { "tur_string_trim", 0 },
    { "unbox", TURI_CAP_UNSAFE },                            /* the native twins of the ptr-deref / raw-malloc builtins */
    { "untrailed-begin", 0 },
    { "untrailed-end", 0 },
    { "unwrap-or", 0 },
    { "unwrap-or-carrier", 0 },
    { "vec-capacity", 0 },
    { "vec-drop-last-o!", 0 },
    { "vec-eq?", 0 },
    { "vec-free", 0 },
    { "vec-free-o", 0 },
    { "vec-get", 0 },
    { "vec-len", 0 },
    { "vec-new", 0 },
    { "vec-new-filled", 0 },
    { "vec-pop!", 0 },
    { "vec-push!", 0 },
    { "vec-push-ptr!", 0 },
    { "vec-set!", 0 },
    { "vec-set-o!", 0 },
    { "with-timeout", TURI_CAP_ASYNC },                      /* scheduler entry points, same gate as (async ...) */
    { "write-async", TURI_CAP_IO },                          /* read(2)/write(2) on a caller-supplied raw fd -- 0/1/2 need no open */
    { "write-temp-file", TURI_CAP_FS },                      /* creates and writes a temp file */
};

/* =========================================================================
 * security-audit-plan S-5: per-native HANDLE SIGNATURE column.
 *
 * The cap column above says which OS capability a native needs; it says nothing
 * about memory safety, because a handle (a vector, map, HAMT, string, iterator,
 * cons cell, ...) is carried as a bare int64 a native casts back to a pointer.
 * In a restricted env the dispatch (eval_apply_driven) consults this table:
 * before the call it refuses any handle argument that is not a live handle of
 * the stated KIND in the env's provenance set, and after the call it registers a
 * freshly-minted handle result / forgets a freed one.  A row lists, per leading
 * argument position, the handle kind the native dereferences there (0 = an
 * ordinary word: a scalar, a stored key/value read back as a carrier, an opaque
 * count), then the result kind and the mint/free flags.
 *
 * What is a handle argument here: a position the native casts to a pointer and
 * dereferences, calls as a function pointer, or stores as a link an internal
 * walk will later dereference.  A key/value that is merely stored and handed
 * back as an int carrier is NOT listed -- forging one is caught when it is later
 * USED as a handle.  A position that reads a C string is CSTR.  The tag decides
 * as much as the registry (prov_arg_ok in eval.c): a tagged string passes only
 * at a CSTR position, a tagged struct only at a STRUCT one, unless the row says
 * the native reads either through its own API (TURI_HSIG_STRUCT_OK / _CSTR_OK);
 * every other tag at a handle position is refused.  Up to TURI_HSIG_MAX_ARGS (6)
 * positions are described, and a described position the call omits is refused.
 *
 * Same layout, same kind; different layout, different kind -- the kind is what
 * keeps one handle from being read as another.  A native whose handle holds
 * words it follows that no row sees (a stored element, a child link) checks
 * them in its own body with turi_prov_check (true when provenance is off).
 *
 * tests/turi/sandbox-eval.c sweeps every capability-free native with forged
 * arguments in a forked child and fails on any crash, so an unclassified native
 * that dereferences its argument is found rather than shipped.
 *
 * Kept in strcmp order and pinned by tests/turi/sandbox-eval.c, which fails if a
 * handle-taking native it knows about loses its row.  Adding a new handle-taking
 * native (a -get/-set/-push/-free/-new over a pointer carrier) adds a row here
 * in the same change. */
static const TuriNativeHandleRow k_handle_rows[] = {
    { "Mock-Time", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_MOCKTIME, TURI_HSIG_MINT },
    { "Mock-Time-free", { TURI_HK_MOCKTIME, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "__identity_duplicate", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_IDENTITY, TURI_HSIG_MINT },
    { "__identity_extract", { TURI_HK_IDENTITY, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__identity_get", { TURI_HK_IDENTITY, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__identity_new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_IDENTITY, TURI_HSIG_MINT },
    { "__inst_Hash_hash_Sym", { TURI_HK_SYM, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__inst_Hash_hash_cstr", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__inst_MapKey_mk_hycmp_Sym", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CMP, TURI_HSIG_MINT },
    { "__inst_MapKey_mk_hycmp_cstr", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CMP, TURI_HSIG_MINT },
    { "__inst_MapKey_mk_hycmp_float", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CMP, TURI_HSIG_MINT },
    { "__inst_MapKey_mk_hycmp_float32", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CMP, TURI_HSIG_MINT },
    { "__inst_MapKey_mk_hycmp_int", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CMP, TURI_HSIG_MINT },
    { "__inst_Serializable_deserialize_bool", { TURI_HK_BYTES, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__inst_Serializable_deserialize_int", { TURI_HK_BYTES, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__inst_Serializable_serialize_bool", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BYTES, TURI_HSIG_MINT },
    { "__inst_Serializable_serialize_int", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BYTES, TURI_HSIG_MINT },
    { "__inst_Show_show_bool", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_cstr", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_float", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_float32", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_int", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_int16", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_int32", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_int8", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_uint16", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_uint32", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_uint64", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__inst_Show_show_uint8", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "__pair_duplicate", { TURI_HK_PAIR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_PAIR, TURI_HSIG_MINT },
    { "__pair_env", { TURI_HK_PAIR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__pair_extract", { TURI_HK_PAIR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__pair_new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_PAIR, TURI_HSIG_MINT },
    { "__pair_val", { TURI_HK_PAIR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-copy!-raw", { TURI_HK_SIZEDBUF, TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-fill!-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-free-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "__sized-buf-get-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-len-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-max-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-min-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-new-raw", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SIZEDBUF, TURI_HSIG_MINT },
    { "__sized-buf-new-zeroed-raw", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SIZEDBUF, TURI_HSIG_MINT },
    { "__sized-buf-set!-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "__sized-buf-sum-raw", { TURI_HK_SIZEDBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "alloc-str", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_OWNED_CSTR, TURI_HSIG_MINT },
    { "async-chan-count", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "async-chan-free", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "async-chan-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CHAN, TURI_HSIG_MINT },
    { "async-chan-try-recv", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "async-chan-try-send", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "bt-bound?", { TURI_HK_BTCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "bt-cell-free", { TURI_HK_BTCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "bt-cell-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BTCELL, TURI_HSIG_MINT },
    { "bt-cons", { TURI_HK_NONE, TURI_HK_BTSTREAM, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BTSTREAM, TURI_HSIG_MINT },
    { "bt-get", { TURI_HK_BTCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "bt-length", { TURI_HK_BTSTREAM, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "bt-lvar-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BTCELL, TURI_HSIG_MINT },
    { "bt-print", { TURI_HK_BTSTREAM, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "bt-set!", { TURI_HK_BTCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "bytes-alloc", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BYTES, TURI_HSIG_MINT },
    { "bytes-data", { TURI_HK_BYTES, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "bytes-free", { TURI_HK_BYTES, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "bytes-len", { TURI_HK_BYTES, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "chan-free", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "chan-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CHAN, TURI_HSIG_MINT },
    { "chan-recv", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "chan-send", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "cons", { TURI_HK_NONE, TURI_HK_CONS, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CONS, TURI_HSIG_MINT },
    { "cstr->parse-int", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "cstr-sub", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "err-val", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "err-val-ptr", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "err?", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "future-cell-free", { TURI_HK_FUTURE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "future-cell-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_FUTURE, TURI_HSIG_MINT },
    { "future-done?", { TURI_HK_FUTURE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "future-free", { TURI_HK_FUTURE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "future-handle", { TURI_HK_FUTURE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "g-cell-free", { TURI_HK_BTCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "g-cell-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BTCELL, TURI_HSIG_MINT },
    { "g-get", { TURI_HK_BTCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "g-set!", { TURI_HK_BTCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "gen-arr-get", { TURI_HK_GENARR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "gen-arr-len", { TURI_HK_GENARR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "gen-arr-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_GENARR, TURI_HSIG_MINT },
    { "gen-arr-push!", { TURI_HK_GENARR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "gen-unwrap", { TURI_HK_GENBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "grid-free", { TURI_HK_GRID, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "grid-get", { TURI_HK_GRID, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "grid-height", { TURI_HK_GRID, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "grid-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_GRID, TURI_HSIG_MINT },
    { "grid-set!", { TURI_HK_GRID, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "grid-width", { TURI_HK_GRID, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "hamt-free", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "hamt-get", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "hamt-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "hamt-set", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "head", { TURI_HK_CONS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "json/array-get", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/array-len", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/array-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/array-push", { TURI_HK_JSON, TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/bool", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/decode", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/decode-file!", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/encode", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/float", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/free", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/get", { TURI_HK_JSON, TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_OPTIONBOX, TURI_HSIG_MINT },
    { "json/get!", { TURI_HK_JSON, TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/get-bool", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/get-float", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/get-int", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/get-string", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/int", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/null", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/object-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/object-put", { TURI_HK_JSON, TURI_HK_CSTR, TURI_HK_JSON, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "json/string", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_JSON, TURI_HSIG_MINT },
    { "json/type", { TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "list-head", { TURI_HK_CONS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "list-length", { TURI_HK_CONS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "list-nil?", { TURI_HK_CONS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "list-tail", { TURI_HK_CONS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "map-assoc-eq", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "map-assoc-eq-o", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "map-count", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "map-dissoc-eq", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "map-dissoc-eq-o", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "map-eq-raw-k?", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_CMP, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "map-eq-raw?", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "map-free", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "map-get-dynamic-as", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "map-get-eq", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "map-get-eq-o", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "map-hamt", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "map-has-eq-o?", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "map-has-eq?", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "map-iter-cur-val-as", { TURI_HK_HAMT_ITER, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "map-merge", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "map-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "mbind", { TURI_HK_BTSTREAM, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BTSTREAM, TURI_HSIG_MINT },
    { "mock-time-get", { TURI_HK_MOCKTIME, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mock-time-set", { TURI_HK_MOCKTIME, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mplus", { TURI_HK_BTSTREAM, TURI_HK_BTSTREAM, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BTSTREAM, TURI_HSIG_MINT },
    { "mreturn", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_BTSTREAM, TURI_HSIG_MINT },
    { "mutex-free", { TURI_HK_MUTEX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "mutex-lock", { TURI_HK_MUTEX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutex-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_MUTEX, TURI_HSIG_MINT },
    { "mutex-try-lock", { TURI_HK_MUTEX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutex-unlock", { TURI_HK_MUTEX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-cap", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-delete!", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-eq-storage?", { TURI_HK_MMSTORAGE, TURI_HK_MMSTORAGE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-free", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "mutmap-get", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-has?", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-len", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_MUTMAP, TURI_HSIG_MINT },
    { "mutmap-set!", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-slot-hash", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-slot-key", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-slot-occupied?", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-slot-value", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "mutmap-storage-field__", { TURI_HK_MUTMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_MMSTORAGE, TURI_HSIG_MINT },
    { "ok-val", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "ok-val-ptr", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "ok?", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "option-eq?", { TURI_HK_OPTIONBOX, TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "option-expect", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "option-free", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE | TURI_HSIG_STRUCT_OK },
    { "option-map", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "option-must", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "option-unwrap", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "option-unwrap-or", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "option-value", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "promise-fulfill", { TURI_HK_FUTURE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-args-head__", { TURI_HK_ARGCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-args-tail__", { TURI_HK_ARGCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_ARGCELL, TURI_HSIG_MINT },
    { "r7rs-cont-capture__", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_R7KCONT, TURI_HSIG_MINT },
    { "r7rs-cont-here?__", { TURI_HK_R7KCONT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-cont-restore__", { TURI_HK_R7KCONT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-idtab-count__", { TURI_HK_R7IDTAB, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-idtab-free__", { TURI_HK_R7IDTAB, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "r7rs-idtab-get__", { TURI_HK_R7IDTAB, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-idtab-new__", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_R7IDTAB, TURI_HSIG_MINT },
    { "r7rs-idtab-put__", { TURI_HK_R7IDTAB, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-add-byte__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-add__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-byte-ref__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-close__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-flush__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-free__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "r7rs-io-len__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-new__", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_R7IO, TURI_HSIG_MINT },
    { "r7rs-io-ok?__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-open__", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_R7IO, TURI_HSIG_MINT },
    { "r7rs-io-peek__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-ready?__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-skip__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "r7rs-io-std__", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_R7IO, TURI_HSIG_MINT },
    { "r7rs-io-str__", { TURI_HK_R7IO, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "result-collect", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_RESULTBOX, TURI_HSIG_MINT },
    { "result-debug", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-display", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-eq?", { TURI_HK_RESULTBOX, TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-error-message", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-expect", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-flat-map", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-free", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE | TURI_HSIG_STRUCT_OK },
    { "result-map", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-map-err", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-must", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-must-msg", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-or", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-or-else", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-partition", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_RESPAIR, TURI_HSIG_MINT },
    { "result-partition-err", { TURI_HK_RESPAIR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "result-partition-ok", { TURI_HK_RESPAIR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "result-unwrap", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-unwrap-err", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "result-unwrap-or", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "schan-close", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "schan-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CHAN, TURI_HSIG_MINT },
    { "schan-recv-value", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schan-send", { TURI_HK_CHAN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-decode", { TURI_HK_SCHEMA, TURI_HK_JSON, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_RESULTBOX, TURI_HSIG_MINT },
    { "schema-decode-abort", { TURI_HK_SCHERRS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-decode-errors", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-decode-ok?", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-decode-value", { TURI_HK_RESULTBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-error-at", { TURI_HK_SCHERRS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHERR, TURI_HSIG_MINT },
    { "schema-error-count", { TURI_HK_SCHERRS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-error-message", { TURI_HK_SCHERRS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-error-path", { TURI_HK_SCHERR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema-error-text", { TURI_HK_SCHERR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema/always", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/ap", { TURI_HK_SCHEMA, TURI_HK_SCHEMA, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/ap-fat", { TURI_HK_SCHEMA, TURI_HK_SCHEMA, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/array", { TURI_HK_SCHEMA, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/bool", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/field", { TURI_HK_SCHEMA, TURI_HK_CSTR, TURI_HK_SCHEMA, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema/field-of", { TURI_HK_CSTR, TURI_HK_SCHEMA, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/float", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/fmap", { TURI_HK_SCHEMA, TURI_HK_CLOSURE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/int", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/kind", { TURI_HK_SCHEMA, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "schema/literal-int", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/literal-str", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/never", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/nil", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/object-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/optional", { TURI_HK_SCHEMA, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/rec", { TURI_HK_CLOSURE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/str", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/transform", { TURI_HK_SCHEMA, TURI_HK_CLOSURE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "schema/union", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SCHEMA, TURI_HSIG_MINT },
    { "seq-gen-done", { TURI_HK_GEN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-gen-done-int", { TURI_HK_GEN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-gen-from-int", { TURI_HK_GEN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_GEN, TURI_HSIG_MINT },
    { "seq-gen-next", { TURI_HK_GEN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_GENBOX, TURI_HSIG_MINT },
    { "seq-gen-next-int", { TURI_HK_GEN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_GENBOX, TURI_HSIG_MINT },
    { "seq-gen-to-int", { TURI_HK_GEN, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_GEN, TURI_HSIG_MINT },
    { "seq-iter", { TURI_HK_GENARR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-list-head", { TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-list-nil?", { TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-list-tail", { TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-make-cons", { TURI_HK_NONE, TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SEQCELL, TURI_HSIG_MINT },
    { "seq-make-none", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SEQCELL, TURI_HSIG_MINT },
    { "seq-make-pair", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SEQCELL, TURI_HSIG_MINT },
    { "seq-make-some", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SEQCELL, TURI_HSIG_MINT },
    { "seq-opt-some?", { TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-opt-unwrap", { TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-out-vec-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SEQVEC, TURI_HSIG_MINT },
    { "seq-out-vec-push!", { TURI_HK_SEQVEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-pair-first", { TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-pair-second", { TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-val-unwrap", { TURI_HK_GENBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-vec-get", { TURI_HK_SEQVEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "seq-vec-len", { TURI_HK_SEQVEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "set-add-eq-o", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "set-count", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "set-del-eq-o", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "set-diff", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "set-eq-cmp?", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "set-eq?", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "set-free", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "set-has-eq-o?", { TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "set-intersect", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "set-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "set-union", { TURI_HK_SETMAP, TURI_HK_SETMAP, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SETMAP, TURI_HSIG_MINT },
    { "slice-free", { TURI_HK_SLICEBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "slice-get", { TURI_HK_SLICEBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "slice-len", { TURI_HK_SLICEBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "slice-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SLICEBOX, TURI_HSIG_MINT },
    { "some?", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "str->int-checked", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "str->sym", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SYM, TURI_HSIG_MINT },
    { "struct-key-cmp", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CMP, TURI_HSIG_MINT },
    { "sym->str", { TURI_HK_SYM, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "sym->syntax", { TURI_HK_SYM, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_CSTR_OK },
    { "sym=?", { TURI_HK_SYM, TURI_HK_SYM, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tail", { TURI_HK_CONS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "task-group-cancel", { TURI_HK_TASKGROUP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "task-group-cancelled?", { TURI_HK_TASKGROUP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "task-group-free", { TURI_HK_TASKGROUP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "task-group-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_TASKGROUP, TURI_HSIG_MINT },
    { "task-group-wait", { TURI_HK_TASKGROUP, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tuple2-eq-carrier?", { TURI_HK_SEQCELL, TURI_HK_SEQCELL, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "tur_hamt_count", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_del", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_del_cstr", { TURI_HK_HAMT, TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_free", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "tur_hamt_get", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_get_cstr", { TURI_HK_HAMT, TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_get_dynamic", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "tur_hamt_has", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_has_cstr", { TURI_HK_HAMT, TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_has_dynamic", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_CMP }, TURI_HK_NONE, 0 },
    { "tur_hamt_iter_advance", { TURI_HK_HAMT_ITER, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_iter_alloc", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT_ITER, TURI_HSIG_MINT },
    { "tur_hamt_iter_cur_hash", { TURI_HK_HAMT_ITER, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_iter_cur_key", { TURI_HK_HAMT_ITER, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_iter_cur_val", { TURI_HK_HAMT_ITER, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_iter_destroy", { TURI_HK_HAMT_ITER, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "tur_hamt_iter_free", { TURI_HK_HAMT_ITER, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "tur_hamt_iter_init", { TURI_HK_HAMT_ITER, TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_iter_next", { TURI_HK_HAMT_ITER, TURI_HK_GENERIC, TURI_HK_GENERIC, TURI_HK_GENERIC }, TURI_HK_NONE, 0 },
    { "tur_hamt_keyeq", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_CMP, TURI_HSIG_MINT },
    { "tur_hamt_merge", { TURI_HK_HAMT, TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_merge_with", { TURI_HK_HAMT, TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_persistent", { TURI_HK_HAMT_TRANS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_retain", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_set", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_set_cstr", { TURI_HK_HAMT, TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT, TURI_HSIG_MINT },
    { "tur_hamt_show", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_transient", { TURI_HK_HAMT, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_HAMT_TRANS, TURI_HSIG_MINT },
    { "tur_hamt_transient_del", { TURI_HK_HAMT_TRANS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_hamt_transient_set", { TURI_HK_HAMT_TRANS, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_reactor_free", { TURI_HK_REACTOR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "tur_sb_finish", { TURI_HK_SBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_sb_len", { TURI_HK_SBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_sb_new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SBUF, TURI_HSIG_MINT },
    { "tur_sb_push_byte", { TURI_HK_SBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_sb_push_cstr", { TURI_HK_SBUF, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_sb_push_string", { TURI_HK_SBUF, TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_byte_at", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_cmp", { TURI_HK_SLICE, TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_empty", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_eq", { TURI_HK_SLICE, TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_hash", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_len", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_release", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "tur_slice_retain", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SLICE, TURI_HSIG_MINT },
    { "tur_slice_sub", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SLICE, TURI_HSIG_MINT },
    { "tur_slice_to_cstr", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_slice_to_string", { TURI_HK_SLICE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_adopt_cstr", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_box_key", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_byte_at", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_cmp", { TURI_HK_STRING, TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_concat", { TURI_HK_STRING, TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_contains", { TURI_HK_STRING, TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_cstr", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_empty", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_ends_with", { TURI_HK_STRING, TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_eq", { TURI_HK_STRING, TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_from_bytes", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_from_cstr", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_from_int", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_hash", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_key_eq_addr", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_len", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_release", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "tur_string_retain", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_slice", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SLICE, TURI_HSIG_MINT },
    { "tur_string_slice_cstr", { TURI_HK_CSTR, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_SLICE, TURI_HSIG_MINT },
    { "tur_string_starts_with", { TURI_HK_STRING, TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "tur_string_substring", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_to_lower", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_to_upper", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "tur_string_trim", { TURI_HK_STRING, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_STRING, TURI_HSIG_MINT },
    { "unwrap-or", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "unwrap-or-carrier", { TURI_HK_OPTIONBOX, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_STRUCT_OK },
    { "vec-capacity", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-drop-last-o!", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-eq?", { TURI_HK_VEC, TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-free", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "vec-free-o", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, TURI_HSIG_FREE },
    { "vec-get", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-len", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-new", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_VEC, TURI_HSIG_MINT },
    { "vec-new-filled", { TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_VEC, TURI_HSIG_MINT },
    { "vec-pop!", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-push!", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-push-ptr!", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-set!", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
    { "vec-set-o!", { TURI_HK_VEC, TURI_HK_NONE, TURI_HK_NONE, TURI_HK_NONE }, TURI_HK_NONE, 0 },
};

const TuriNativeHandleRow *turi_native_handle_table(size_t *n_out) {
    if (n_out) *n_out = sizeof k_handle_rows / sizeof k_handle_rows[0];
    return k_handle_rows;
}

const TuriNativeHandleRow *turi_native_handle_find(const char *name) {
    if (!name) return NULL;
    size_t lo = 0, hi = sizeof k_handle_rows / sizeof k_handle_rows[0];
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int c = strcmp(name, k_handle_rows[mid].name);
        if (c == 0) return &k_handle_rows[mid];
        if (c < 0) hi = mid; else lo = mid + 1;
    }
    return NULL;
}

const TuriNativeCapRow *turi_native_cap_table(size_t *n_out) {
    if (n_out) *n_out = sizeof k_rows / sizeof k_rows[0];
    return k_rows;
}

const TuriNativeCapRow *turi_native_cap_find(const char *name) {
    if (!name) return NULL;
    size_t lo = 0, hi = sizeof k_rows / sizeof k_rows[0];
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int c = strcmp(name, k_rows[mid].name);
        if (c == 0) return &k_rows[mid];
        if (c < 0) hi = mid; else lo = mid + 1;
    }
    return NULL;
}

const char *turi_caps_describe(TuriCaps caps, char *buf, size_t n) {
    static const struct { TuriCaps bit; const char *name; } k_names[] = {
        { TURI_CAP_IO,       "io"       },
        { TURI_CAP_FFI,      "ffi"      },
        { TURI_CAP_INLINE_C, "inline-c" },
        { TURI_CAP_ASYNC,    "async"    },
        { TURI_CAP_UNSAFE,   "unsafe"   },
        { TURI_CAP_IMPORT,   "import"   },
        { TURI_CAP_FS,       "fs"       },
        { TURI_CAP_PROC,     "proc"     },
        { TURI_CAP_ENV,      "env"      },
    };
    if (!buf || n == 0) return "";
    buf[0] = '\0';
    size_t used = 0;
    for (size_t i = 0; i < sizeof k_names / sizeof k_names[0]; i++) {
        if (!(caps & k_names[i].bit)) continue;
        size_t len = strlen(k_names[i].name);
        size_t sep = used ? 1 : 0;
        if (used + sep + len + 1 > n) break;
        if (sep) buf[used++] = ',';
        memcpy(buf + used, k_names[i].name, len + 1);
        used += len;
    }
    return buf;
}
